
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, yy_size_t len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 82
#define YY_END_OF_BUFFER 83
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[260] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   83,   61,   59,   60,   61,   46,
       51,   44,   14,   41,   43,   26,   29,   22,   28,   54,
       27,   56,   56,   17,   24,   34,   25,   32,   58,   38,
       40,   14,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   35,   13,   37,
       76,   75,   74,   76,   70,   69,   64,   63,   67,   66,
       77,   78,   82,   80,   81,   80,   60,   45,   16,   47,
       13,   18,    0,   42,   14,   15,   18,    0,   53,    0,
       54,   50,   49,   17,   54,   55,    0,    0,    0,   15,

       33,   30,   31,   15,   57,   58,    0,   39,   23,   23,
       23,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,    8,    3,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   48,    0,   36,
        0,   73,   71,   71,   72,    0,   68,    0,   62,    0,
       65,   79,   18,    0,    0,   54,   52,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,    2,   58,   58,
       58,    4,    8,    0,   58,   58,   58,   58,   58,   58,
       58,    4,    0,   54,    5,   58,    6,    9,   58,   58,
       58,   58,   58,   58,    0,   58,   58,    0,   58,   58,

       58,   58,   58,   58,   58,   58,   12,   10,   58,   58,
       58,   58,    0,   58,   58,    0,   58,   11,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,    0,   58,
        0,   58,    2,    7,   58,   58,   58,    0,   58,   21,
        0,    1,   58,   58,   58,    0,   58,    1,    0,   58,
        0,    0,   58,    0,    0,   19,    0,   20,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    7,    8,    1,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   18,   18,   18,   18,   18,   18,   21,   22,   23,
       24,   25,    1,    1,   26,   27,   27,   27,   28,   27,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   30,
       29,   29,   29,   29,   29,   29,   29,   31,   29,   29,
       32,   33,   34,   35,   36,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   46,   47,   48,   49,   50,
       51,   52,   46,   53,   54,   55,   56,   57,   58,   59,
       60,   46,   61,   62,   63,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[64] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    3,    3,    3,
        1,    1,    1,    1,    1,    3,    3,    3,    2,    2,
        2,    1,    1,    1,    1,    2,    3,    3,    3,    3,
        3,    3,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        1,    1,    1
    } ;

static const flex_int16_t yy_base[269] =
    {   0,
        0,    0,   61,   62,   52,   56,   79,  105,   60,   64,
       82,   84,   89,   90,  638,  639,  639,  639,  634,  612,
      639,  611,  102,  639,   87,  610,   79,  639,   88,  133,
      138,  140,  155,  585,  639,   90,  584,   84,  604,  639,
      125,  582,  199,  112,  257,  126,   63,  261,  127,  135,
      153,  137,  158,  259,  263,  260,  161,  639,  241,  265,
      639,  639,  268,  273,  639,  270,  639,  275,  639,  278,
      639,  639,  639,  639,  639,  589,  639,  639,  639,  639,
      639,  579,  280,  639,  639,  639,  639,  282,  639,  585,
      328,  639,  639,  639,  335,  342,  354,    0,  360,  574,

      639,  639,  639,  573,  639,  591,  285,  639,  639,  639,
      590,  131,  266,  271,  290,  136,  272,  286,  287,  292,
      289,  288,  283,  294,  588,  299,  308,  313,  173,  347,
      355,  339,  361,  364,  373,  378,  381,  639,  388,  639,
      390,  639,  639,  639,  639,  393,  639,  395,  639,  397,
      639,  639,  639,  394,  402,  421,  639,  384,  399,  404,
      400,  401,  422,  407,  412,  424,  177,  587,  413,  382,
      423,  425,  585,  561,  426,  428,  432,  440,  450,  443,
      451,  583,  450,  482,  582,  461,  580,  579,  454,  434,
      455,  459,  462,  469,  551,  473,  474,  526,  477,  475,

      479,  480,  483,  487,  484,  490,  573,  572,  488,  491,
      500,  493,  520,  494,  501,  528,  502,  567,  504,  507,
      515,  512,  517,  519,  518,  522,  525,  527,  521,  530,
      510,  528,  538,  558,  532,  539,  544,  263,  545,  639,
      548,  639,  550,  553,  554,  250,  555,  639,  273,  556,
      149,  139,  557,  143,  138,  639,  124,  639,  639,  610,
      613,  616,  619,  622,  625,  627,  630,  163
    } ;

static const flex_int16_t yy_def[269] =
    {   0,
      259,    1,  260,  260,  261,  261,  262,  262,  263,  263,
      264,  264,  265,  265,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  266,  259,
      259,  259,  259,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  259,  259,  259,
      259,  259,  259,  267,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  268,  259,  259,

      259,  259,  259,  259,  259,  266,  259,  259,  259,  259,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  259,  266,  266,  266,  266,  266,  266,
      266,  266,  259,  259,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  259,  266,  266,  259,  266,  266,

      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  259,  266,  266,  259,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  259,  266,
      259,  266,  266,  266,  266,  266,  266,  259,  266,  259,
      259,  259,  266,  266,  266,  259,  266,  259,  259,  266,
      259,  259,  266,  259,  259,  259,  259,  259,    0,  259,
      259,  259,  259,  259,  259,  259,  259,  259
    } ;

static const flex_int16_t yy_nxt[703] =
    {   0,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   33,   33,
       34,   35,   36,   37,   38,   39,   39,   39,   39,   39,
       39,   40,   16,   41,   42,   43,   39,   44,   45,   46,
       47,   48,   49,   39,   50,   39,   39,   39,   51,   39,
       52,   53,   54,   55,   56,   39,   57,   39,   39,   39,
       58,   59,   60,   62,   62,  105,   63,   63,   66,   66,
       66,   66,   66,   66,   66,   66,   70,   70,   70,   70,
       70,   70,   70,   70,   72,   73,   72,   73,   83,   84,
       86,   75,   75,   64,   64,   68,   68,   68,   68,   76,

       76,   87,   79,   85,   68,   68,   68,  103,  104,   80,
      118,   81,  100,  101,  105,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   81,  107,  108,  105,  105,
       68,   68,   68,  105,   88,   89,   82,  105,  105,  105,
       83,   68,   68,   68,   68,   68,   68,   90,   92,   91,
       91,   91,   91,   93,   95,  105,   96,   96,   96,   96,
      105,   94,  112,  105,  113,  157,  117,   97,  258,   95,
       98,   99,   99,   99,   99,  105,  125,  124,  107,  105,
       97,  158,   97,  126,  127,  162,   88,  174,  257,  128,
      129,  195,  256,  255,  130,   97,  254,  137,   98,  109,

      109,  110,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  111,  111,  111,  111,  109,
      109,  109,  109,  109,  111,  111,  111,  111,  111,  111,
      109,  109,  109,  109,  111,  111,  111,  111,  111,  106,
      111,  111,  111,  111,  111,  111,  106,  111,  111,  111,
      111,  106,  111,  106,  111,  111,  111,  111,  111,  105,
      109,  105,  105,  105,   81,  105,  139,  140,  105,  141,
      142,  146,  147,  105,  105,  144,  148,  149,  145,  150,
      151,   83,   84,   88,   89,  105,  107,  108,  105,  105,
      105,  105,  105,  114,  105,  131,  105,  119,  252,  132,

      115,  105,  138,  133,  251,  145,  159,  116,  120,  121,
      105,  122,  246,  163,  145,  105,  123,  134,  139,  136,
      135,  141,  145,  146,  160,  145,  161,  145,  148,   88,
       89,  150,  169,   83,  165,   88,   88,   89,  107,  164,
      168,  105,  166,  167,   91,   91,   91,   91,  170,  105,
      171,   91,   91,   91,   91,  154,   95,  105,   99,   99,
       99,   99,  172,  105,  173,  155,  105,  155,  154,   97,
      156,  156,  156,  156,   95,  105,   99,   99,   99,   99,
      105,   88,   97,  105,  105,  175,  105,   97,   88,  139,
      140,  141,  142,  177,  146,  147,  148,  149,  150,  151,

       97,  105,  105,  105,  176,  183,  105,  183,  178,  105,
      184,  184,  184,  184,  105,  105,  179,  180,  156,  156,
      156,  156,   88,   89,  105,  105,  105,  105,  105,  181,
      105,  185,  188,  182,  105,  186,  105,  156,  156,  156,
      156,  139,  105,  141,  187,  105,  146,  125,  148,  188,
      150,  125,  105,  105,  189,  190,  105,  105,  191,  193,
      194,  105,  192,  105,  105,  197,  184,  184,  184,  184,
      200,  105,  199,  196,   88,  105,  105,  105,  209,  105,
      202,  105,  105,   88,   89,  105,  105,  201,  203,  105,
      105,  207,  105,  105,  204,  105,  105,  206,  184,  184,

      184,  184,  105,  105,  105,  205,  105,  187,  208,  105,
      210,  173,  228,  217,  105,  218,  211,  105,  220,  105,
      105,  105,  223,  212,  105,  214,  215,  105,  224,  105,
      105,  219,  105,  221,  105,   88,  222,  225,  226,  241,
      242,  105,  230,  227,  232,  182,  105,  105,  208,  241,
      248,  241,  242,  233,  185,  105,  105,  105,  105,  105,
      105,  234,  208,  240,  235,  238,  239,  249,  168,  105,
      231,  188,  229,  236,  105,  105,  187,  237,  216,  207,
      213,  105,  105,  247,  105,  105,  198,  105,  244,  105,
      105,  243,  105,  105,  245,  234,   79,   86,  253,   87,

      218,  241,  153,  243,  152,   85,  105,  102,   79,  250,
       61,   61,   61,   65,   65,   65,   67,   67,   67,   69,
       69,   69,   71,   71,   71,   74,   74,   74,  106,  106,
      143,  143,  143,   85,   79,   78,   77,  259,   15,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,

      259,  259
    } ;

static const flex_int16_t yy_chk[703] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    4,   47,    3,    4,    5,    5,
        5,    5,    6,    6,    6,    6,    9,    9,    9,    9,
       10,   10,   10,   10,   11,   11,   12,   12,   25,   25,
       27,   13,   14,    3,    4,    7,    7,    7,    7,   13,

       14,   29,   27,   36,    7,    7,    7,   38,   38,   23,
       47,   29,   36,   36,   44,    7,    7,    7,    7,    7,
        7,    8,    8,    8,    8,   23,   41,   41,   46,   49,
        8,    8,    8,  112,   30,   30,   23,   50,  116,   52,
       25,    8,    8,    8,    8,    8,    8,   30,   31,   30,
       30,   30,   30,   31,   32,   51,   32,   32,   32,   32,
       53,   31,   44,   57,   44,  268,   46,   32,  257,   33,
       32,   33,   33,   33,   33,  129,   50,   49,   41,  167,
       32,  112,   33,   50,   50,  116,   30,  129,  255,   51,
       52,  167,  254,  252,   53,   33,  251,   57,   32,   43,

       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   45,
       43,   54,   56,   48,   59,   55,   60,   60,  113,   63,
       63,   66,   66,  114,  117,   64,   68,   68,   64,   70,
       70,   83,   83,   88,   88,  123,  107,  107,  118,  119,
      122,  121,  115,   45,  120,   54,  124,   48,  249,   54,

       45,  126,   59,   55,  246,   64,  113,   45,   48,   48,
      127,   48,  238,  117,   64,  128,   48,   55,   60,   56,
       55,   63,   64,   66,  114,   64,  115,   64,   68,   91,
       91,   70,  123,   83,  119,   88,   95,   95,  107,  118,
      122,  132,  120,  121,   91,   91,   91,   91,  124,  130,
      126,   95,   95,   95,   95,   91,   96,  131,   96,   96,
       96,   96,  127,  133,  128,   97,  134,   97,   91,   96,
       97,   97,   97,   97,   99,  135,   99,   99,   99,   99,
      136,   91,   96,  137,  170,  130,  158,   99,   95,  139,
      139,  141,  141,  132,  146,  146,  148,  148,  150,  150,

       99,  159,  161,  162,  131,  154,  160,  154,  133,  164,
      154,  154,  154,  154,  165,  169,  134,  135,  155,  155,
      155,  155,  156,  156,  163,  171,  166,  172,  175,  136,
      176,  158,  170,  137,  177,  159,  190,  156,  156,  156,
      156,  139,  178,  141,  160,  180,  146,  164,  148,  161,
      150,  169,  179,  181,  162,  162,  189,  191,  163,  165,
      166,  192,  163,  186,  193,  172,  183,  183,  183,  183,
      176,  194,  175,  171,  156,  196,  197,  200,  190,  199,
      178,  201,  202,  184,  184,  203,  205,  177,  179,  204,
      209,  181,  206,  210,  179,  212,  214,  180,  184,  184,

      184,  184,  211,  215,  217,  179,  219,  186,  189,  220,
      191,  192,  212,  199,  222,  200,  193,  221,  202,  223,
      225,  224,  205,  194,  226,  196,  197,  227,  206,  228,
      232,  201,  230,  203,  235,  184,  204,  209,  210,  233,
      233,  236,  215,  211,  217,  228,  237,  239,  214,  241,
      241,  243,  243,  219,  222,  244,  245,  247,  250,  253,
      234,  220,  224,  231,  221,  229,  230,  244,  232,  218,
      216,  223,  213,  225,  208,  207,  226,  227,  198,  236,
      195,  188,  187,  239,  185,  182,  174,  173,  235,  168,
      125,  233,  111,  106,  237,  247,  104,  100,  250,   90,

      253,  241,   82,  243,   76,   42,   39,   37,   34,  245,
      260,  260,  260,  261,  261,  261,  262,  262,  262,  263,
      263,  263,  264,  264,  264,  265,  265,  265,  266,  266,
      267,  267,  267,   26,   22,   20,   19,   15,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,

      259,  259
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "gocompiler.l"
#line 2 "gocompiler.l"
    /* João Ricardo Miranda Botelho 2019155348  */
    #include <ctype.h>
    #include <stdbool.h>
    #include <stdlib.h>
    #include <string.h>
    int line = 1, column = 1;
    int x = 0, y = 0;
    int lx = 0, ly = 0;

    char octal[100];
    int octalPos = 0;
    bool octalError = false;
    bool semicolon = false;

    char* trim_whitespace(char* string){
      char* output =  (char*)malloc(strlen(string)*sizeof(char));
      int i = -1;
      while(!isspace(string[++i])) output[i] = string[i];
      output[i] = 0;
      return output;
    }

    bool in_comment = 0, in_literal = 0;
    char* atoupper(char* str){
        for (int i = 0; str[i] != 0; i++) str[i] = toupper(str[i]);
        return str;
    }

    void validOctal(char n){
       if (!octalError) octalError = !(n >= '0' && n <= '7');
    }

    void addOctal(char c){
      octal[octalPos++] = c;
    }

    bool textComparer(FILE* f1, FILE* f2){
      int pos = 0;
      char a = 0, b = 0;
      printf("started comparing...\n");
      while(a != EOF && b != EOF){
        a = fgetc(f1);
        b = fgetc(f2);
        if (a != b){
          printf("ERROR ON POS %d\na = %c\tb = %c\n", pos, a, b);
          return 0;
        }
        pos++;
      }
      return (a == EOF && b == EOF);
    }
#line 736 "lex.yy.c"

#line 738 "lex.yy.c"

#define INITIAL 0
#define STRLIT 1
#define OCTAL 2
#define HEX 3
#define DEC 4
#define LINE_COMMENT 5
#define COMMENT 6

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			yy_size_t yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 70 "gocompiler.l"

#line 72 "gocompiler.l"
                                /* Reserved declared    */

#line 966 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 260 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 639 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 74 "gocompiler.l"
{fprintf(yyout, "RETURN\nSEMICOLON\n"); yyless(yyleng-1);}
	YY_BREAK
case 2:
#line 76 "gocompiler.l"
case 3:
#line 77 "gocompiler.l"
case 4:
#line 78 "gocompiler.l"
case 5:
YY_RULE_SETUP
#line 78 "gocompiler.l"
{fprintf(yyout, "%s\n", atoupper(yytext)); column += yyleng;}
	YY_BREAK
/*  Reserved undeclared */
case 6:
#line 83 "gocompiler.l"
case 7:
#line 84 "gocompiler.l"
case 8:
#line 85 "gocompiler.l"
case 9:
#line 86 "gocompiler.l"
case 10:
#line 87 "gocompiler.l"
case 11:
#line 88 "gocompiler.l"
case 12:
#line 89 "gocompiler.l"
case 13:
#line 90 "gocompiler.l"
case 14:
#line 91 "gocompiler.l"
case 15:
#line 92 "gocompiler.l"
case 16:
#line 93 "gocompiler.l"
case 17:
#line 94 "gocompiler.l"
case 18:
YY_RULE_SETUP
#line 94 "gocompiler.l"
{fprintf(yyout, "RESERVED(%s)\n", yytext); column += yyleng;}
	YY_BREAK
/*  Args and puncts */
case 19:
YY_RULE_SETUP
#line 98 "gocompiler.l"
{fprintf(yyout, "PRINT\n"); column += yyleng;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 99 "gocompiler.l"
{fprintf(yyout, "PARSEINT\n"); column += yyleng;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 100 "gocompiler.l"
{fprintf(yyout, "CMDARGS\n"); column += yyleng;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 101 "gocompiler.l"
{fprintf(yyout, "COMMA\n"); column += yyleng;}
	YY_BREAK
case 23:
/* rule 23 can match eol */
YY_RULE_SETUP
#line 102 "gocompiler.l"
{fprintf(yyout, "BLANKID\n"); column += yyleng; yyless(1);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 103 "gocompiler.l"
{fprintf(yyout, "SEMICOLON\n"); column += yyleng;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 104 "gocompiler.l"
{fprintf(yyout, "ASSIGN\n"); column += yyleng;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 105 "gocompiler.l"
{fprintf(yyout, "STAR\n"); column += yyleng;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 106 "gocompiler.l"
{fprintf(yyout, "DIV\n"); column += yyleng;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 107 "gocompiler.l"
{fprintf(yyout, "MINUS\n"); column += yyleng;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 108 "gocompiler.l"
{fprintf(yyout, "PLUS\n"); column += yyleng;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 109 "gocompiler.l"
{fprintf(yyout, "EQ\n"); column += yyleng;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 110 "gocompiler.l"
{fprintf(yyout, "GE\n"); column += yyleng;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 111 "gocompiler.l"
{fprintf(yyout, "GT\n"); column += yyleng;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 112 "gocompiler.l"
{fprintf(yyout, "LE\n"); column += yyleng;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 113 "gocompiler.l"
{fprintf(yyout, "LT\n"); column += yyleng;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 114 "gocompiler.l"
{fprintf(yyout, "LBRACE\n"); column += yyleng;}
	YY_BREAK
case 36:
/* rule 36 can match eol */
YY_RULE_SETUP
#line 115 "gocompiler.l"
{fprintf(yyout, "RBRACE\nSEMICOLON\n"); yyless(yyleng-1);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 116 "gocompiler.l"
{fprintf(yyout, "RBRACE\n"); column += yyleng;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 117 "gocompiler.l"
{fprintf(yyout, "LSQ\n"); column += yyleng;}
	YY_BREAK
case 39:
/* rule 39 can match eol */
YY_RULE_SETUP
#line 118 "gocompiler.l"
{fprintf(yyout, "RSQ\nSEMICOLON\n"); yyless(yyleng-1);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 119 "gocompiler.l"
{fprintf(yyout, "RSQ\n"); column += yyleng;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 120 "gocompiler.l"
{fprintf(yyout, "LPAR\n"); column += yyleng;}
	YY_BREAK
case 42:
/* rule 42 can match eol */
YY_RULE_SETUP
#line 121 "gocompiler.l"
{fprintf(yyout, "RPAR\nSEMICOLON\n");}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 122 "gocompiler.l"
{fprintf(yyout, "RPAR\n"); column += yyleng;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 123 "gocompiler.l"
{fprintf(yyout, "MOD\n"); column += yyleng;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 124 "gocompiler.l"
{fprintf(yyout, "NE\n"); column += yyleng;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 125 "gocompiler.l"
{fprintf(yyout, "NOT\n"); column += yyleng;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 126 "gocompiler.l"
{fprintf(yyout, "AND\n"); column += yyleng;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 127 "gocompiler.l"
{fprintf(yyout, "OR\n"); column += yyleng;}
	YY_BREAK
/* Comments */
case 49:
YY_RULE_SETUP
#line 131 "gocompiler.l"
{BEGIN LINE_COMMENT; column += yyleng;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 132 "gocompiler.l"
{BEGIN COMMENT; in_comment = 1; x = column, y = line;}
	YY_BREAK
/*  Numbers and literals    */
case 51:
YY_RULE_SETUP
#line 136 "gocompiler.l"
{
                                    BEGIN STRLIT;
                                    fprintf(yyout, "STRLIT(\"");
                                    column += yyleng;
                                    in_literal = 1;
                                    ly = line, lx = column;
                                }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 143 "gocompiler.l"
{
                                    BEGIN HEX;
                                    char x = yytext[yyleng-1];
                                    yytext[yyleng-1] = 0;
                                    fprintf(yyout, "INTLIT(%s", yytext);
                                    yytext[yyleng-1] = x;
                                    column += yyleng-1; yyless(yyleng-1);}
	YY_BREAK
case 53:
/* rule 53 can match eol */
YY_RULE_SETUP
#line 150 "gocompiler.l"
{
                                    fprintf(yyout, "REALLIT(%s)\nSEMICOLON\n",
                                            trim_whitespace(yytext));
                                    yyless(yyleng-1);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 154 "gocompiler.l"
{fprintf(yyout, "REALLIT(%s)\n", yytext); column += yyleng;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 155 "gocompiler.l"
{
                                    BEGIN OCTAL;
                                    addOctal('0');
                                    column += yyleng-1; yyless(yyleng-1);
                                }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 160 "gocompiler.l"
{
                                    BEGIN DEC;
                                    fprintf(yyout, "INTLIT(");
                                    column += yyleng-1; yyless(yyleng-1);
                                }
	YY_BREAK
case 57:
/* rule 57 can match eol */
YY_RULE_SETUP
#line 165 "gocompiler.l"
{
                                    yytext[yyleng-1] = 0;
                                    fprintf(yyout, "ID(%s)\nSEMICOLON\n", yytext);
                                    yytext[yyleng-1] = '\n'; ; yyless(yyleng-1);
                                }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 170 "gocompiler.l"
{fprintf(yyout, "ID(%s)\n", yytext); column += yyleng;}
	YY_BREAK
/*  Regular lines   */
case 59:
YY_RULE_SETUP
#line 174 "gocompiler.l"
{column+=yyleng;}
	YY_BREAK
case 60:
/* rule 60 can match eol */
YY_RULE_SETUP
#line 175 "gocompiler.l"
{line++;column = 1;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 176 "gocompiler.l"
{
                                fprintf(yyout, "Line %d, column %d: illegal character (%c)\n",
                                        line, column+=yyleng, yytext[0]);
                                }
	YY_BREAK
/*  Hex */
case 62:
/* rule 62 can match eol */
YY_RULE_SETUP
#line 183 "gocompiler.l"
{fprintf(yyout, "%c", yytext[0]); semicolon = true; yyless(yyleng-1);}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 184 "gocompiler.l"
{ECHO;column+=yyleng;}
	YY_BREAK
case 64:
/* rule 64 can match eol */
YY_RULE_SETUP
#line 185 "gocompiler.l"
{
                                    fprintf(yyout, ")\n");
                                    if (semicolon) fprintf(yyout, "SEMICOLON\n");
                                    BEGIN 0; yyless(0);
                                    semicolon = false;
                                }
	YY_BREAK
/*  Dec */
case 65:
/* rule 65 can match eol */
YY_RULE_SETUP
#line 194 "gocompiler.l"
{fprintf(yyout, "%c", yytext[0]); semicolon = true; yyless(yyleng-1);}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 195 "gocompiler.l"
{ECHO; column+=yyleng;}
	YY_BREAK
case 67:
/* rule 67 can match eol */
YY_RULE_SETUP
#line 196 "gocompiler.l"
{
                                    fprintf(yyout, ")\n");
                                    if (semicolon) fprintf(yyout, "SEMICOLON\n");
                                    BEGIN 0; yyless(0);
                                    semicolon = false;
                                }
	YY_BREAK
/*  Octal   */
case 68:
/* rule 68 can match eol */
YY_RULE_SETUP
#line 205 "gocompiler.l"
{addOctal(yytext[0]); validOctal(yytext[0]); yyless(yyleng-1); semicolon = true;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 206 "gocompiler.l"
{addOctal(yytext[0]); validOctal(yytext[0]); column+=yyleng;}
	YY_BREAK
case 70:
/* rule 70 can match eol */
YY_RULE_SETUP
#line 207 "gocompiler.l"
{
                                octal[octalPos] = 0;
                                if (octalError){
                                  fprintf(yyout, "Line %d, column %d: invalid octal constant (%s)\n",
                                         line, column - octalPos + 1, octal);
                                  octalError = false;
                                }else fprintf(yyout, "INTLIT(%s)\n", octal);
                                if (semicolon)fprintf(yyout, "SEMICOLON\n");
                                if (yytext[0] == '\n'){ column = 1; line++;}
                                semicolon = false;
                                octalPos = 0;
                                BEGIN 0; yyless(0);
                                }
	YY_BREAK
/*  Str Literal */
case 71:
/* rule 71 can match eol */
YY_RULE_SETUP
#line 223 "gocompiler.l"
{
                                    fprintf(yyout, "\")\nLine %d, column %d: invalid escape sequence (%c)\n"
                                    "STRLIT(\"",
                                    line, (column+=yyleng)-1, yytext[yyleng-1]);
                                }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 228 "gocompiler.l"
{ECHO; column += yyleng;}
	YY_BREAK
case 73:
/* rule 73 can match eol */
YY_RULE_SETUP
#line 229 "gocompiler.l"
{BEGIN 0; fprintf(yyout, "\")\nSEMICOLON\n"); yyless(yyleng-1);}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 230 "gocompiler.l"
{BEGIN 0; fprintf(yyout, "\")\n"); column += yyleng; in_literal = 0;}
	YY_BREAK
case 75:
/* rule 75 can match eol */
YY_RULE_SETUP
#line 231 "gocompiler.l"
{ECHO; line++;column = 1;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 232 "gocompiler.l"
{ECHO; column += yyleng;}
	YY_BREAK
/* Line Comment */
case 77:
YY_RULE_SETUP
#line 236 "gocompiler.l"
{column += yyleng;}
	YY_BREAK
case 78:
/* rule 78 can match eol */
YY_RULE_SETUP
#line 237 "gocompiler.l"
{BEGIN 0; column = 1; line++;}
	YY_BREAK
/*  Comment */
case 79:
YY_RULE_SETUP
#line 241 "gocompiler.l"
{BEGIN 0; column += yyleng; in_comment = 0;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 242 "gocompiler.l"
{column += yyleng;}
	YY_BREAK
case 81:
/* rule 81 can match eol */
YY_RULE_SETUP
#line 243 "gocompiler.l"
{line++; column = 1;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 244 "gocompiler.l"
ECHO;
	YY_BREAK
#line 1474 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STRLIT):
case YY_STATE_EOF(OCTAL):
case YY_STATE_EOF(HEX):
case YY_STATE_EOF(DEC):
case YY_STATE_EOF(LINE_COMMENT):
case YY_STATE_EOF(COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 260 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 260 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 259);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 244 "gocompiler.l"


int main()
{
  /*
FILE* f = fopen("../testes/factorial.dgo", "r");
FILE* f1 = fopen("../testes/factorial.out", "r");
FILE* f2 = fopen("texto_output.txt", "w");
yyin = f;
yyout = f2;
*/
yylex();
if (in_literal) fprintf(yyout, "Line %d, column %d: unterminated literal\n", ly, lx);
if (in_comment) fprintf(yyout, "Line %d, column %d: unterminated comment\n", y, x);
/*
fclose(f2);
f2 = fopen("texto_output.txt", "r");
if (textComparer(f1, f2))printf("Works!\n");
else printf("?\n");
fclose(f2);
fclose(f);
fclose(f1);
*/
return 0;
}
int yywrap()
{
return 1;
}

